language: node_js
node_js:
  - '0.8'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'npm install'
  - 'bower install'
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
script: node_modules/karma/bin/karma start karma.conf.js
